version: '3.8'
services:
    omdb:
        build: .
        command: gunicorn base.wsgi:application --bind 0.0.0.0:8081
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
        - 8081
        depends_on:
        - db
    db:
        image: postgres
        volumes:
            - postgres_database_volume:/var/lib/postgresql/data
        env_file:
        - ./config/db/database_env
    nginx:
        container_name: "nginx"
        build: ./config/nginx/dev_conf.d
        volumes:
            - static_volume:/home/app/web/staticfiles
        ports:
        - 8443:8081
        depends_on:
        - omdb
volumes:
    postgres_database_volume:
    static_volume: