version: '3.8'
services:
    omdb:
        build: .
        command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
        expose:
        - 8000
        depends_on:
        - db
    db:
        image: postgres
        volumes:
            - postgres_database_volume:/var/lib/postgresql/data
        ports:
        - "6666:5432"
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=episode
    nginx:
      container_name: "nginx"
      build: ./config/nginx/dev_conf.d
      volumes:
          - static_volume:/home/app/web/staticfiles
      ports:
        - 80:80
      depends_on:
        - db
volumes:
    postgres_database_volume:
    static_volume: