# Generated by Django 4.1 on 2022-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="actors",
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name="episode",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
    ]
