# Generated by Django 4.1 on 2022-09-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0002_episode_actors_episode_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="actors",
            new_name="actor",
        ),
    ]
