# Generated by Django 4.1 on 2022-09-14 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_rename_actors_episode_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="published",
            field=models.DateField(
                blank=True, default=datetime.datetime(2022, 9, 14, 21, 54, 38, 516078)
            ),
        ),
    ]
