# Generated by Django 4.1 on 2022-09-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0003_actor_remove_episode_actor_alter_episode_language_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="actors",
            new_name="actor",
        ),
    ]
