# Generated by Django 4.1 on 2022-09-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0004_rename_actors_episode_actor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="episode",
            old_name="actor",
            new_name="actors",
        ),
    ]
