# Generated by Django 4.1 on 2022-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0005_alter_comment_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="published",
            field=models.DateField(auto_now_add=True),
        ),
    ]
